### ISSUE TITLE
crash windows 7

### ISSUE THREAD

**Issue by sonoro1234** [programmatom/OutOfPhase#1]
Hi,
On windows 7 32 bits Installed .NET 4.6.1, run OutOfPhase (release or debug) and program crashed inmediately.

Best
victor bombi

**Comment by programmatom** [comment]
32-bit: there were multiple issues with 32 bit. I have hopefully cleaned them up, and in the process split the build targets into 64-bit ("bin\x64") and 32-bit ("bin\x86"), be sure to pick the latter.

Win7: not yet able to test that, as setting up a Win7 partition today has gone badly. I would like to do some basic testing there before resolving the work item.

**Comment by sonoro1234** [comment]
Thanks!!. Program don't crash on init now.
Trying to figure how it works.

**Comment by programmatom** [comment]
As you have seen, it is still a work-in-progress. How to use it is not
obvious, and documentation is non-existent. But I hope to get some basic
examples available in the next few days. It might make much more sense
at that point. I will send you a link when I have posted something.

Thanks for trying it!

Tom

On 1/31/2016 1:46 AM, Victor Bombi wrote:

> Thanks!!. Program don't crash on init now.
> Trying to figure how it works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programmatom/OutOfPhase/issues/1#issuecomment-177448499.

## 

dtszepun@gmail.com | PGP Key 0x5BD6BF7A | Fingerprint 7F96 4101 6A9A
3FC5 43BA 74F7 BC38 5B93 5BD6 BF7A

**Comment by programmatom** [comment]
I have posted some working example files for Out Of Phase on the
following page:
http://outofphasemusic.com/docs/examples.html

It is a small start since there many non-obvious details, but I am much
better and writing code than I am at writing documentation, so this side
of things will only come in bits and pieces.

Thanks,
Tom

On 1/31/2016 1:46 AM, Victor Bombi wrote:

> Thanks!!. Program don't crash on init now.
> Trying to figure how it works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programmatom/OutOfPhase/issues/1#issuecomment-177448499.

## 

dtszepun@gmail.com | PGP Key 0x5BD6BF7A | Fingerprint 7F96 4101 6A9A
3FC5 43BA 74F7 BC38 5B93 5BD6 BF7A
